import type { Metadata } from 'next'
import { Inter, Manrope } from 'next/font/google'
import { ReactNode } from 'react'
import './globals.css'

import { Authenticate } from '@repo/ui'
import { Toaster } from 'sonner'

const headingFont = Manrope({
	subsets: ['latin'],
	variable: '--font-heading',
})

const bodyFont = Inter({
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${headingFont.variable} ${bodyFont.className} antialiased transition-colors duration-300`}>
				<Authenticate>{children}</Authenticate>
				<Toaster />
			</body>
		</html>
	)
}
