import type { Metadata } from 'next'
import { Manrope, Playfair_Display } from 'next/font/google'
import { ReactNode } from 'react'

import Providers from '@/components/Providers'
import StyledComponentsRegistry from '@/components/Registry'
import './globals.css'

const playfair = Playfair_Display({
	subsets: ['latin'],
	variable: '--font-serif',
})

const manrope = Manrope({
	subsets: ['latin'],
	variable: '--font-sans',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${playfair.variable} ${manrope.variable} antialiased`}>
				<StyledComponentsRegistry>
					<Providers>{children}</Providers>
				</StyledComponentsRegistry>
			</body>
		</html>
	)
}
