import { GeistSans } from 'geist/font/sans'
import type { Metadata } from 'next'
import { Geist_Mono } from 'next/font/google'
import { ReactNode } from 'react'
import './globals.css'

import DefaultLayout from '@/layouts/DefaultLayout'
import { Authenticate } from '@repo/ui'
import { Toaster } from 'sonner'

const monoFont = Geist_Mono({
	subsets: ['latin'],
	variable: '--font-geist-mono',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${GeistSans.className} ${monoFont.variable} antialiased`}>
				<Authenticate>
					<DefaultLayout>{children}</DefaultLayout>
				</Authenticate>
				<Toaster />
			</body>
		</html>
	)
}
