import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {ReactNode} from "react";

import "./globals.css";
import DefaultLayout from "@/layouts/DefaultLayout";
import Authenticate from "@/components/Authenticate";
import {Toaster} from "@/components/ui/sonner";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-gray-50 text-[#111827]`}
      >
      <Authenticate>
          <DefaultLayout>
              {children}
          </DefaultLayout>
      </Authenticate>

      <Toaster />
      </body>
    </html>
  );
}
