import type { Metadata } from 'next'
import {
	JetBrains_Mono,
	Playfair_Display,
	Plus_Jakarta_Sans,
} from 'next/font/google'
import { ReactNode } from 'react'
import './globals.css'

const serifFont = Playfair_Display({
	subsets: ['latin'],
	variable: '--font-serif',
})

const sansFont = Plus_Jakarta_Sans({
	subsets: ['latin'],
	variable: '--font-sans',
})

const monoFont = JetBrains_Mono({
	subsets: ['latin'],
	variable: '--font-mono',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${sansFont.variable} ${serifFont.variable} ${monoFont.variable} antialiased`}>
				{children}
			</body>
		</html>
	)
}
